import { PageContents, PageContentsEntry } from '../../components/PageContents/PageContents';

const entries: PageContentsEntry[] = [
  { id: 'overview', label: 'Overview' },
  { id: 'conventions', label: 'Conventions' },
  { id: 'conventions-envelope', label: 'Response envelope', indent: true },
  { id: 'conventions-pagination', label: 'Pagination', indent: true },
  { id: 'conventions-sorting', label: 'Sorting', indent: true },
  { id: 'conventions-amounts', label: 'Amounts and units', indent: true },
  { id: 'errors', label: 'Errors' },
  { id: 'status', label: 'Status' },
  { id: 'blocks', label: 'Blocks' },
  { id: 'blocks-list', label: 'List', indent: true },
  { id: 'blocks-get', label: 'Get a block', indent: true },
  { id: 'blocks-hash', label: 'By hash', indent: true },
  { id: 'transactions', label: 'Transactions' },
  { id: 'transactions-get', label: 'Get a tx', indent: true },
  { id: 'transactions-raw', label: 'Raw tx', indent: true },
  { id: 'addresses', label: 'Addresses' },
  { id: 'addresses-list', label: 'Rich list', indent: true },
  { id: 'addresses-get', label: 'Get an address', indent: true },
  { id: 'addresses-tx', label: 'Tx history', indent: true },
  { id: 'addresses-utxos', label: 'UTXOs', indent: true },
  { id: 'mempool', label: 'Mempool' },
  { id: 'mempool-snapshot', label: 'Snapshot', indent: true },
  { id: 'mempool-fee-histogram', label: 'Fee histogram', indent: true },
  { id: 'mempool-timeline', label: 'Timeline', indent: true },
  { id: 'superblocks', label: 'Superblocks' },
  { id: 'superblocks-list', label: 'List', indent: true },
  { id: 'superblocks-get', label: 'Get one', indent: true },
  { id: 'cpids', label: 'CPIDs' },
  { id: 'cpids-get', label: 'Researcher detail', indent: true },
  { id: 'cpids-blocks', label: 'Blocks staked', indent: true },
  { id: 'cpids-leaderboard', label: 'Leaderboard', indent: true },
  { id: 'polls', label: 'Polls' },
  { id: 'polls-list', label: 'List', indent: true },
  { id: 'polls-get', label: 'Get a poll', indent: true },
  { id: 'beacons', label: 'Beacons' },
  { id: 'beacons-cpid', label: 'History per CPID', indent: true },
  { id: 'network', label: 'Network' },
  { id: 'network-now', label: 'Current snapshot', indent: true },
  { id: 'network-history', label: 'History', indent: true },
  { id: 'network-difficulty', label: 'Difficulty history', indent: true },
  { id: 'metrics', label: 'Metrics' },
  { id: 'metrics-buckets', label: 'Bucketed time series', indent: true },
  { id: 'metrics-leaderboard-magnitude', label: 'Magnitude leaderboard', indent: true },
  { id: 'metrics-research-split', label: 'Research / block split', indent: true },
  { id: 'metrics-beacon-flux', label: 'Beacon flux', indent: true },
  { id: 'metrics-staker-mix', label: 'Staker mix', indent: true },
  { id: 'metrics-fee-percentiles', label: 'Fee percentiles', indent: true },
  { id: 'metrics-wealth', label: 'Wealth distribution', indent: true },
  { id: 'metrics-cohort-retention', label: 'Cohort retention', indent: true },
  { id: 'metrics-beacon-survival', label: 'Beacon survival', indent: true },
  { id: 'search', label: 'Search' },
];

export function Contents() {
  return <PageContents entries={entries} />;
}
