-- Mark tx_inputs that re-claim an already-spent UTXO. Early Gridcoin
-- (Halford era, ~Jan 2015) accepted multiple coinstake txes referencing
-- the same kernel UTXO in vin[0] — verified on-chain for UTXO
-- 984651000883676deae602abba65eb64e8b04c009ff068cea8bd9d3a0eee1697:1
-- (spent by 8 distinct coinstake txes across blocks 113925..113945).
-- The chain's UTXO set only debits the first claim; later claims are
-- phantom and must not contribute to address_balance_history.sent or
-- the cumulative sum(delta) that downstream balance queries depend on.
--
-- The indexer (see PhantomSpendDetector) sets this column to true for
-- every re-claim; address_balance_history is computed with the phantom
-- debits cancelled so a voter's balance at poll-start reconciles with
-- the daemon's scanforunspent view (and so PollWeightAggregator never
-- has to insert a negative weight into the UInt64 votes.weight column).
ALTER TABLE tx_inputs ADD COLUMN IF NOT EXISTS is_phantom_spend Bool DEFAULT false;
